"""Aggregate report generation for batch scan results.

Produces Markdown, JSON, and HTML reports summarizing multiple project scans.
HTML reports are single-file with no external CDN dependencies.
"""

from __future__ import annotations

import html
import json
from typing import Any


def _escape(text: str) -> str:
    """HTML-escape text and truncate if too long."""
    escaped = html.escape(str(text))
    if len(escaped) > 500:
        return escaped[:497] + "..."
    return escaped


def _status_badge(status: str) -> str:
    """Return HTML badge for status."""
    colors = {"pass": "#22c55e", "warn": "#eab308", "fail": "#ef4444", "error": "#ef4444"}
    color = colors.get(status, "#6b7280")
    return f'<span style="background:{color};color:white;padding:2px 8px;border-radius:4px;font-size:0.85em">{html.escape(status)}</span>'


def _score_color(score: int) -> str:
    """Return CSS color for score."""
    if score >= 80:
        return "#22c55e"
    if score >= 50:
        return "#eab308"
    return "#ef4444"


def generate_aggregate_json_report(batch_result: dict[str, Any], output_path: str | None = None) -> str:
    """Generate JSON report from batch scan result.

    Args:
        batch_result: BatchResult.to_dict() output.
        output_path: Optional file path to write to.

    Returns:
        JSON string.
    """
    text = json.dumps(batch_result, indent=2, ensure_ascii=False)
    if output_path:
        from pathlib import Path
        Path(output_path).write_text(text, encoding="utf-8")
    return text


def generate_aggregate_markdown_report(batch_result: dict[str, Any]) -> str:
    """Generate Markdown report from batch scan result.

    Args:
        batch_result: BatchResult.to_dict() output.

    Returns:
        Markdown string.
    """
    workspace = batch_result.get("workspace", {})
    summary = batch_result.get("summary", {})
    projects = batch_result.get("projects", [])
    cache = batch_result.get("cache", {})

    lines = ["# Batch Scan Report\n"]

    # Workspace info
    lines.append(f"**Workspace:** {workspace.get('name', 'unnamed')}")
    lines.append(f"**Projects:** {workspace.get('project_count', 0)}")
    lines.append(f"**Duration:** {batch_result.get('duration_seconds', 0):.1f}s")
    lines.append("")

    # Summary
    lines.append("## Summary\n")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Pass | {summary.get('pass', 0)} |")
    lines.append(f"| Warn | {summary.get('warn', 0)} |")
    lines.append(f"| Fail | {summary.get('fail', 0)} |")
    lines.append(f"| Error | {summary.get('error', 0)} |")
    lines.append(f"| Average Score | {summary.get('average_score', 0)} |")
    lines.append("")

    # Project table
    lines.append("## Projects\n")
    lines.append("| ID | Path | Profile | Status | Score | Blocking | Important | Advisory | Cache |")
    lines.append("|----|------|---------|--------|-------|----------|-----------|----------|-------|")
    for proj in projects:
        fc = proj.get("finding_counts", {})
        cache_mark = "hit" if proj.get("cache_hit") else "miss"
        error_mark = f" (error: {proj['error'][:40]})" if proj.get("error") else ""
        lines.append(
            f"| `{_md_escape(proj.get('id', ''))}` "
            f"| {_md_escape(proj.get('path', ''))} "
            f"| {proj.get('profile', '')} "
            f"| {proj.get('status', 'error')}{error_mark} "
            f"| {proj.get('score', 0)} "
            f"| {fc.get('blocking', 0)} "
            f"| {fc.get('important', 0)} "
            f"| {fc.get('advisory', 0)} "
            f"| {cache_mark} |"
        )
    lines.append("")

    # Failed/error projects
    failed = [p for p in projects if p.get("status") == "fail" or p.get("error")]
    if failed:
        lines.append("## Failed / Error Projects\n")
        for proj in failed:
            if proj.get("error"):
                lines.append(f"- **{proj['id']}**: Error — {proj['error']}")
            else:
                lines.append(f"- **{proj['id']}**: Score {proj.get('score', 0)}, status {proj.get('status')}")
        lines.append("")

    # Cache summary
    if cache.get("total", 0) > 0:
        lines.append("## Cache\n")
        lines.append(f"- Total: {cache.get('total', 0)}")
        lines.append(f"- Hits: {cache.get('hits', 0)}")
        lines.append(f"- Misses: {cache.get('misses', 0)}")
        lines.append(f"- Errors: {cache.get('errors', 0)}")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Generated by oss-paper-ci {batch_result.get('version', 'unknown')}*")
    lines.append("")

    return "\n".join(lines)


def generate_aggregate_html_report(batch_result: dict[str, Any]) -> str:
    """Generate single-file HTML report from batch scan result.

    No external CDN dependencies. All user text is HTML-escaped.

    Args:
        batch_result: BatchResult.to_dict() output.

    Returns:
        HTML string.
    """
    workspace = batch_result.get("workspace", {})
    summary = batch_result.get("summary", {})
    projects = batch_result.get("projects", [])
    cache = batch_result.get("cache", {})
    version = batch_result.get("version", "unknown")
    duration = batch_result.get("duration_seconds", 0)

    ws_name = _escape(workspace.get("name", "unnamed"))
    project_count = workspace.get("project_count", 0)
    avg_score = summary.get("average_score", 0)
    pass_count = summary.get("pass", 0)
    warn_count = summary.get("warn", 0)
    fail_count = summary.get("fail", 0)
    error_count = summary.get("error", 0)

    # Build project rows
    project_rows = ""
    for proj in projects:
        pid = _escape(proj.get("id", ""))
        ppath = _escape(proj.get("path", ""))
        profile = _escape(proj.get("profile", ""))
        status = proj.get("status", "unknown")
        score = proj.get("score", 0)
        fc = proj.get("finding_counts", {})
        cache_hit = "hit" if proj.get("cache_hit") else "miss"
        error = _escape(proj.get("error", ""))

        error_cell = f'<span style="color:#ef4444">{error}</span>' if error else ""
        project_rows += f"""<tr>
<td><code>{pid}</code></td>
<td>{ppath}</td>
<td>{profile}</td>
<td>{_status_badge(status)}</td>
<td style="color:{_score_color(score)};font-weight:bold">{score}</td>
<td>{fc.get('blocking', 0)}</td>
<td>{fc.get('important', 0)}</td>
<td>{fc.get('advisory', 0)}</td>
<td>{cache_hit}</td>
<td>{error_cell}</td>
</tr>
"""

    # Cache section
    cache_section = ""
    if cache.get("total", 0) > 0:
        cache_section = f"""
<h2>Cache</h2>
<div class="summary">
<div><div class="label">Total</div><div>{cache.get('total', 0)}</div></div>
<div><div class="label">Hits</div><div>{cache.get('hits', 0)}</div></div>
<div><div class="label">Misses</div><div>{cache.get('misses', 0)}</div></div>
<div><div class="label">Errors</div><div>{cache.get('errors', 0)}</div></div>
</div>
"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Batch Scan Report — {ws_name}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 1100px; margin: 2em auto; padding: 0 1em; color: #1f2937; line-height: 1.5; }}
h1 {{ border-bottom: 2px solid #e5e7eb; padding-bottom: 0.3em; }}
h2 {{ margin-top: 1.5em; }}
.score {{ font-size: 3em; font-weight: bold; color: {_score_color(avg_score)}; }}
.summary {{ display: flex; gap: 2em; margin: 1em 0; flex-wrap: wrap; }}
.summary div {{ background: #f9fafb; padding: 1em; border-radius: 8px; min-width: 120px; text-align: center; }}
.summary .label {{ font-size: 0.85em; color: #6b7280; }}
table {{ width: 100%; border-collapse: collapse; margin: 1em 0; font-size: 0.9em; }}
th, td {{ text-align: left; padding: 8px; border-bottom: 1px solid #e5e7eb; }}
th {{ background: #f3f4f6; }}
code {{ background: #f3f4f6; padding: 2px 4px; border-radius: 3px; font-size: 0.9em; }}
.metadata {{ color: #6b7280; font-size: 0.85em; margin-top: 2em; }}
.metadata p {{ margin: 0.2em 0; }}
.footer {{ margin-top: 2em; padding-top: 1em; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 0.85em; }}
</style>
</head>
<body>
<h1>Batch Scan Report</h1>

<div class="metadata">
<p><strong>Workspace:</strong> {ws_name}</p>
<p><strong>Tool:</strong> oss-paper-ci {_escape(version)}</p>
<p><strong>Duration:</strong> {duration:.1f}s</p>
</div>

<div class="summary" id="summary">
<div><div class="label">Average Score</div><div class="score">{avg_score}</div></div>
<div><div class="label">Projects</div><div>{project_count}</div></div>
<div><div class="label">Pass</div><div style="color:#22c55e;font-weight:bold">{pass_count}</div></div>
<div><div class="label">Warn</div><div style="color:#eab308;font-weight:bold">{warn_count}</div></div>
<div><div class="label">Fail</div><div style="color:#ef4444;font-weight:bold">{fail_count}</div></div>
<div><div class="label">Error</div><div style="color:#ef4444;font-weight:bold">{error_count}</div></div>
</div>

<h2>Projects</h2>
<table>
<tr><th>ID</th><th>Path</th><th>Profile</th><th>Status</th><th>Score</th><th>Blocking</th><th>Important</th><th>Advisory</th><th>Cache</th><th>Error</th></tr>
{project_rows}
</table>

{cache_section}

<div class="footer">
Generated by <a href="https://github.com/Akastella/oss-paper-ci">oss-paper-ci</a> {_escape(version)}
</div>
</body>
</html>"""


def _md_escape(text: str) -> str:
    """Escape text for Markdown table cells."""
    return str(text).replace("|", "\\|").replace("\n", " ")
