"""Markdown report generation for GitHub PR comments."""

from __future__ import annotations

from typing import TYPE_CHECKING

from oss_paper_ci.models import Status

if TYPE_CHECKING:
    from oss_paper_ci.models import Report


_STATUS_EMOJI = {
    "pass": "✅",
    "warn": "⚠️",
    "fail": "❌",
    "unknown": "❓",
}

_SEVERITY_EMOJI = {
    "info": "ℹ️",
    "warning": "⚠️",
    "error": "❌",
}


def generate_markdown_report(
    report: Report,
    output_path: str | None = None,
    verbose: bool = False,
) -> str:
    """Generate a Markdown report suitable for GitHub PR comments.

    Args:
        report: The Report object.
        output_path: If provided, write to this file.
        verbose: If True, show all check details with evidence.
                 If False, show summary, blocking issues, and top recommendations only.

    Returns:
        Markdown string.
    """
    lines: list[str] = []

    # Header
    lines.append("# 🔬 oss-paper-ci Report")
    lines.append("")

    # Summary
    s = report.summary
    status_emoji = _STATUS_EMOJI.get(s.status, "")
    lines.append(f"**Score: {s.score}/100** {status_emoji}")
    lines.append("")
    lines.append(f"| Metric | Count |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Errors | {s.counts.get('error', 0)} |")
    lines.append(f"| Warnings | {s.counts.get('warning', 0)} |")
    lines.append(f"| Info | {s.counts.get('info', 0)} |")
    lines.append("")

    # Key risks
    errors = [c for c in report.checks if c.status == Status.FAIL]
    warnings = [c for c in report.checks if c.status == Status.WARN]

    if errors:
        lines.append("## ❌ Critical Issues")
        lines.append("")
        for c in errors:
            lines.append(f"- **{c.id}**: {c.message}")
        lines.append("")

    if warnings:
        lines.append("## ⚠️ Warnings")
        lines.append("")
        for c in warnings:
            lines.append(f"- **{c.id}**: {c.message}")
        lines.append("")

    # Top recommendations (always shown)
    if report.recommendations:
        lines.append("## 💡 Recommendations")
        lines.append("")
        for rec in report.recommendations:
            lines.append(f"- {rec}")
        lines.append("")

    if verbose:
        # Verbose mode: full check details with evidence
        lines.append("## 📋 Check Details")
        lines.append("")
        lines.append("| ID | Title | Status | Severity |")
        lines.append("|----|-------|--------|----------|")
        for c in report.checks:
            s_val = c.status.value if hasattr(c.status, 'value') else c.status
            sev_val = c.severity.value if hasattr(c.severity, 'value') else c.severity
            s_emoji = _STATUS_EMOJI.get(s_val, "")
            sev_emoji = _SEVERITY_EMOJI.get(sev_val, "")
            lines.append(f"| {c.id} | {c.title} | {s_emoji} {s_val} | {sev_emoji} {sev_val} |")
        lines.append("")

        # Evidence and recommendations for non-passing checks
        non_passing = [c for c in report.checks if c.status != Status.PASS]
        if non_passing:
            lines.append("## 🔍 Evidence & Recommendations")
            lines.append("")
            for c in non_passing:
                lines.append(f"### {c.id}: {c.title}")
                lines.append("")
                if c.message:
                    lines.append(f"**Finding:** {c.message}")
                    lines.append("")
                if c.evidence:
                    lines.append("**Evidence:**")
                    for e in c.evidence:
                        lines.append(f"- `{e}`")
                    lines.append("")
                if c.recommendation:
                    lines.append(f"**Recommendation:** {c.recommendation}")
                    lines.append("")

    # Disclaimer
    lines.append("---")
    lines.append("")
    lines.append(
        "> **Disclaimer:** This tool evaluates repository *reproducibility readiness*, "
        "not paper quality, correctness, novelty, or likelihood of acceptance. "
        "A high score does not guarantee reproducibility; a low score does not mean the "
        "research is flawed. It is a checklist for engineering completeness."
    )
    lines.append("")
    lines.append(f"*Generated by oss-paper-ci v{report.version}*")

    text = "\n".join(lines)
    if output_path:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(text)
    return text
