"""Internationalization templates for dossier output.

Provides translated text fragments for en, zh-CN, ja.
"""

from __future__ import annotations

TEMPLATES: dict[str, dict[str, str]] = {
    "en": {
        "title": "Reproducibility Dossier",
        "executive_summary": "Executive Summary",
        "evidence_map": "Evidence Map",
        "risk_register": "Risk Register",
        "remediation_plan": "Remediation Plan",
        "author_checklist": "Author Checklist",
        "reviewer_summary": "Reviewer Summary",
        "maintainer_roadmap": "Maintainer Roadmap",
        "next_steps": "Next Steps",
        "limitations": "Limitations",
        "non_claims": "What This Does NOT Mean",
        "category": "Category",
        "item": "Item",
        "status": "Status",
        "source": "Source",
        "why_it_matters": "Why It Matters",
        "action": "Action",
        "priority": "Priority",
        "rationale": "Rationale",
        "effort": "Effort",
        "severity": "Severity",
        "likelihood": "Likelihood",
        "impact": "Impact",
        "evidence": "Evidence",
        "mitigation": "Mitigation",
        "present": "Present",
        "missing": "Missing",
        "partial": "Partial",
        "unknown": "Unknown",
        "blocking": "Blocking",
        "non_blocking": "Non-blocking",
        "status_ready": "Ready",
        "status_needs_work": "Needs Work",
        "status_blocked": "Blocked",
        "status_unknown": "Unknown",
        "confidence_low": "Low",
        "confidence_medium": "Medium",
        "confidence_high": "High",
        "disclaimer": (
            "This dossier is an automated assessment of reproducibility readiness. "
            "It does not judge paper quality, correctness, or significance. "
            "A high score does not guarantee reproduction. "
            "A low score does not mean the research is flawed."
        ),
        "author_intro": (
            "This section shows what you can do to improve your repository's "
            "reproducibility. The items are ordered by priority."
        ),
        "reviewer_intro": (
            "This section summarizes the reproducibility evidence available "
            "in the repository. It does not make accept/reject recommendations."
        ),
        "maintainer_intro": (
            "This section provides a roadmap for improving reproducibility "
            "across multiple repositories in your organization."
        ),
        "issue_header": "## Reproducibility Checklist\n",
        "pr_comment_header": "## Reproducibility Summary\n",
        "generated_by": "Generated by oss-paper-ci",
    },
    "zh-CN": {
        "title": "复现档案",
        "executive_summary": "概要",
        "evidence_map": "证据清单",
        "risk_register": "风险登记",
        "remediation_plan": "整改计划",
        "author_checklist": "作者清单",
        "reviewer_summary": "审稿摘要",
        "maintainer_roadmap": "维护者路线图",
        "next_steps": "下一步",
        "limitations": "限制",
        "non_claims": "以下结论不成立",
        "category": "类别",
        "item": "项目",
        "status": "状态",
        "source": "来源",
        "why_it_matters": "重要性",
        "action": "行动",
        "priority": "优先级",
        "rationale": "原因",
        "effort": "工作量",
        "severity": "严重程度",
        "likelihood": "可能性",
        "impact": "影响",
        "evidence": "证据",
        "mitigation": "缓解措施",
        "present": "已提供",
        "missing": "缺失",
        "partial": "部分提供",
        "unknown": "未知",
        "blocking": "阻塞",
        "non_blocking": "非阻塞",
        "status_ready": "就绪",
        "status_needs_work": "需要改进",
        "status_blocked": "被阻塞",
        "status_unknown": "未知",
        "confidence_low": "低",
        "confidence_medium": "中",
        "confidence_high": "高",
        "disclaimer": (
            "本档案是复现准备度的自动化评估，不判断论文质量、正确性或重要性。"
            "高分不保证复现成功，低分不意味着研究有缺陷。"
        ),
        "author_intro": (
            "以下内容说明如何改进仓库的复现准备度，按优先级排列。"
        ),
        "reviewer_intro": (
            "以下内容总结仓库中的复现证据，不提供录用/拒稿建议。"
        ),
        "maintainer_intro": (
            "以下内容为组织内多个仓库的复现治理提供路线图。"
        ),
        "issue_header": "## 复现清单\n",
        "pr_comment_header": "## 复现摘要\n",
        "generated_by": "由 oss-paper-ci 生成",
    },
    "ja": {
        "title": "再現ドシエ",
        "executive_summary": "概要",
        "evidence_map": "エビデンスマップ",
        "risk_register": "リスクレジスタ",
        "remediation_plan": "改善計画",
        "author_checklist": "著者チェックリスト",
        "reviewer_summary": "査読者向けサマリー",
        "maintainer_roadmap": "メンテナ向けロードマップ",
        "next_steps": "次のステップ",
        "limitations": "制限事項",
        "non_claims": "以下は成り立たない結論",
        "category": "カテゴリ",
        "item": "項目",
        "status": "ステータス",
        "source": "ソース",
        "why_it_matters": "重要性",
        "action": "アクション",
        "priority": "優先度",
        "rationale": "理由",
        "effort": "作業量",
        "severity": "深刻度",
        "likelihood": "可能性",
        "impact": "影響",
        "evidence": "エビデンス",
        "mitigation": "緩和策",
        "present": "あり",
        "missing": "なし",
        "partial": "一部",
        "unknown": "不明",
        "blocking": "ブロッキング",
        "non_blocking": "ノンブロッキング",
        "status_ready": "準備完了",
        "status_needs_work": "要改善",
        "status_blocked": "ブロック中",
        "status_unknown": "不明",
        "confidence_low": "低",
        "confidence_medium": "中",
        "confidence_high": "高",
        "disclaimer": (
            "このドシエは再現準備度の自動評価です。論文の品質、正確性、重要性を判断するものではありません。"
            "高スコアは再現成功を保証するものではありません。"
            "低スコアは研究に欠陥があることを意味するものではありません。"
        ),
        "author_intro": (
            "このセクションでは、リポジトリの再現準備度を改善するための方法を優先度順に示します。"
        ),
        "reviewer_intro": (
            "このセクションでは、リポジトリの再現エビデンスを要約します。採択/拒否の推奨は行いません。"
        ),
        "maintainer_intro": (
            "このセクションでは、組織内の複数リポジトリの再現性改善ロードマップを提供します。"
        ),
        "issue_header": "## 再現チェックリスト\n",
        "pr_comment_header": "## 再現サマリー\n",
        "generated_by": "oss-paper-ci で生成",
    },
}


def get_template(language: str, key: str) -> str:
    """Get a translated template string."""
    lang_templates = TEMPLATES.get(language, TEMPLATES["en"])
    return lang_templates.get(key, TEMPLATES["en"].get(key, key))


def get_all_templates(language: str) -> dict[str, str]:
    """Get all templates for a language."""
    return TEMPLATES.get(language, TEMPLATES["en"])
