"""Ecosystem-aware file templates for adoption scaffolding.

Provides templates for reproducibility.yml, data/README.md,
results/README.md, GitHub Actions workflow, and other scaffolding files.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class ScaffoldTemplate:
    """A template for a scaffoldable file."""
    id: str
    title: str
    path: str
    description: str
    risk: str = "low"  # low, medium, high
    requires_confirmation: bool = False
    content: str = ""


def generate_reproducibility_yml(
    ecosystems: list[dict] | None = None,
    project_name: str = "my-paper",
    project_type: str = "analysis",
) -> str:
    """Generate a reproducibility.yml template based on detected ecosystems."""
    eco = ecosystems[0] if ecosystems else {}
    eco_id = eco.get("id", "python")
    env_type = eco_id if eco_id in ("python", "r", "julia", "other") else "other"

    # Build install commands from ecosystem
    install_cmds = eco.get("install_plan", [])
    run_cmds = eco.get("run_plan", [])
    install_cmd = install_cmds[0] if install_cmds else "echo 'Add your install command'"
    run_cmd = run_cmds[0] if run_cmds else "echo 'Add your run command'"

    # Detect environment file
    env_files = eco.get("environment_files", [])
    env_file = env_files[0] if env_files else "requirements.txt"

    lines = [
        "# OSS-Paper-CI Reproducibility Contract",
        f"# Generated by oss-paper-ci scaffold",
        "",
        f'version: "0.3"',
        f"project_name: {project_name}",
        f"project_type: {project_type}",
        "",
        "paper:",
        '  path: "paper.pdf"',
        "  bibliography: []",
        "",
        "environment:",
        f"  type: {env_type}",
        f'  file: "{env_file}"',
        "",
        "data:",
        "  - id: main-data",
        '    path: "data/"',
        '    availability: "public"',
        '    source: ""',
        "",
        "experiments:",
        "  - id: main-experiment",
        '    description: "Main experiment"',
        f'    command: "{run_cmd}"',
        "    timeout_seconds: 3600",
        "    safe_to_run: true",
        "    expected_outputs:",
        '      - "results/"',
        "",
        "figures: []",
        "",
        "results:",
        "  - id: main-results",
        '    path: "results/"',
        '    generated_by: "main-experiment"',
        "",
        "ci:",
        "  smoke_experiment: main-experiment",
        "  min_score: 60",
        "  fail_on_regression: false",
    ]
    return "\n".join(lines) + "\n"


def generate_data_readme() -> str:
    """Generate a data/README.md template."""
    return """# Data

This directory contains the data used in this research.

## Contents

<!-- List your datasets here -->

- `example.csv` — Example dataset

## Data sources

<!-- Describe where the data comes from -->

## Data access

<!-- Describe how to access the data -->

## License

<!-- Describe the data license or usage terms -->
"""


def generate_results_readme() -> str:
    """Generate a results/README.md template."""
    return """# Results

This directory contains the results generated by the experiments.

## Contents

- `metrics.json` — Key metrics from the main experiment
- `figures/` — Generated figures
- `tables/` — Generated tables

## Reproducing results

To regenerate these results, run:

```bash
# Add your reproduction command here
```
"""


def generate_figures_readme() -> str:
    """Generate a figures/README.md template."""
    return """# Figures

This directory contains figures generated by the experiments.

## Contents

<!-- List your figures here -->

- `figure1.png` — Description of figure 1

## Generating figures

To regenerate these figures, run:

```bash
# Add your figure generation command here
```
"""


def generate_github_workflow(
    ecosystems: list[dict] | None = None,
    profile: str = "default",
) -> str:
    """Generate a GitHub Actions workflow for oss-paper-ci."""
    eco = ecosystems[0] if ecosystems else {}
    eco_id = eco.get("id", "python")

    # Build setup step based on ecosystem
    if eco_id == "python":
        setup = """      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'"""
        install = "pip install -r requirements.txt"
    elif eco_id == "r":
        setup = """      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'"""
        install = "Rscript -e 'renv::restore()'"
    elif eco_id == "julia":
        setup = """      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'"""
        install = "julia --project=. -e 'using Pkg; Pkg.instantiate()'"
    elif eco_id == "node":
        setup = """      - uses: actions/setup-node@v4
        with:
          node-version: '20'"""
        install = "npm ci"
    else:
        setup = "      # Add your environment setup here"
        install = "# Add your install command here"

    lines = [
        "name: Reproducibility Check",
        "",
        "on:",
        "  push:",
        "    branches: [main]",
        "  pull_request:",
        "    branches: [main]",
        "",
        "jobs:",
        "  check:",
        "    runs-on: ubuntu-latest",
        "    steps:",
        "      - uses: actions/checkout@v4",
        "",
        setup,
        "",
        "      - name: Install dependencies",
        f"        run: {install}",
        "",
        "      - name: Run oss-paper-ci",
        "        uses: Akastella/oss-paper-ci@v1",
        "        with:",
        f'          profile: "{profile}"',
        '          format: "markdown"',
    ]
    return "\n".join(lines) + "\n"


def generate_oss_paper_ci_yml(profile: str = "default") -> str:
    """Generate an oss-paper-ci.yml config file."""
    return f"""# OSS-Paper-CI Configuration
version: 1
profile: {profile}

paths:
  include:
    - "."
  exclude:
    - ".git"
    - "node_modules"
    - "__pycache__"
    - ".venv"

thresholds:
  pass_score: 85
  warn_score: 60
  fail_under: 50

reports:
  default_format: markdown
  include_recommendations: true

ci:
  github_annotations: true
  step_summary: true
"""


def generate_citation_cff(project_name: str = "My Paper") -> str:
    """Generate a CITATION.cff template."""
    return f"""cff-version: 1.2.0
title: "{project_name}"
message: "If you use this software, please cite it using these metadata."
type: software
authors:
  - family-names: "Last Name"
    given-names: "First Name"
"""


def get_scaffold_templates(
    ecosystems: list[dict] | None = None,
    project_name: str = "my-paper",
) -> list[ScaffoldTemplate]:
    """Get all available scaffold templates."""
    templates = []

    templates.append(ScaffoldTemplate(
        id="reproducibility-yml",
        title="Add reproducibility.yml",
        path="reproducibility.yml",
        description="Reproducibility contract defining experiments, data, and environment.",
        risk="low",
        content=generate_reproducibility_yml(ecosystems, project_name),
    ))

    templates.append(ScaffoldTemplate(
        id="data-readme",
        title="Add data/README.md",
        path="data/README.md",
        description="Documentation for the data directory.",
        risk="low",
        content=generate_data_readme(),
    ))

    templates.append(ScaffoldTemplate(
        id="results-readme",
        title="Add results/README.md",
        path="results/README.md",
        description="Documentation for the results directory.",
        risk="low",
        content=generate_results_readme(),
    ))

    templates.append(ScaffoldTemplate(
        id="github-workflow",
        title="Add GitHub Actions workflow",
        path=".github/workflows/oss-paper-ci.yml",
        description="CI workflow for reproducibility checking.",
        risk="low",
        content=generate_github_workflow(ecosystems),
    ))

    templates.append(ScaffoldTemplate(
        id="oss-paper-ci-yml",
        title="Add oss-paper-ci.yml",
        path="oss-paper-ci.yml",
        description="Configuration file for oss-paper-ci.",
        risk="low",
        content=generate_oss_paper_ci_yml(),
    ))

    return templates
